# Setup
title: Not Pure Poole
description: A simple, beautiful, and powerful Jekyll theme for blogs
url: https://vszhub.github.io
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

  name: Naswima Akter (Prova)
  url: https://github.com/naswima/
  email: nakter5@fordham.edu
